import type { Metadata } from 'next'
import { Saira_Condensed } from 'next/font/google'
import './globals.css'
import Header from '../components/Header/Header'
import Footer from '../components/Footer'
import SessionProvider  from './SessionProvider'

const sairaCondensed = Saira_Condensed({
  weight: ["400","700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: 'HeadsUp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${sairaCondensed.className}`}>
        <SessionProvider>
          <Header />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  )
}
