import type { Metadata } from 'next'
import { Sansita } from 'next/font/google'
import './globals.css'
import Header from '../components/Header/Header'
import Footer from '../components/Footer'
import SessionProvider  from './SessionProvider'
const sansita = Sansita({
  weight: ["400"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: 'HeadsUp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${sansita.className}`}>
        <SessionProvider>
          <Header />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  )
}
